version: "3.9"

services:
  db:
    image: postgres:16
    container_name: afisha_db
    environment:
      POSTGRES_DB: afisha
      POSTGRES_USER: afisha
      POSTGRES_PASSWORD: afisha
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U afisha -d afisha"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: afisha_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: afisha
      DB_PASSWORD: afisha
      DB_NAME: afisha
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: afisha_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: afisha_cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNmJjNzc5NzUwZmE1OGIwNTZjMjMyYjY4ZGQxN2I4ZTEiLCJ0IjoiNTA5ZmIyMmUtYzE2OS00NmYxLThkODctNGRkNTI3NmZiYWE5IiwicyI6Ik1UQTFZalJoT1dJdFptVXlOaTAwWldKaUxXRm1ORE10WW1NeU5ERmpORGcyTmpVMSJ9
    # cloudflared в той же сети, что и frontend/backend
    depends_on:
      - frontend

volumes:
  db_data:
